#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldrs.ls -> dist/ldrs.js ..."
./node_modules/.bin/lsc -cbp src/ldrs.ls > dist/ldrs.js
echo "build src/ldrs.styl -> dist/ldrs.css ..."
./node_modules/.bin/stylus -p src/ldrs.styl > dist/ldrs.css
echo "minifying ldrs.js ..."
./node_modules/.bin/uglifyjs dist/ldrs.js > dist/ldrs.min.js
echo "minifying ldrs.css ..."
./node_modules/.bin/uglifycss dist/ldrs.css > dist/ldrs.min.css
echo "copy dist files to web ..."
mkdir -p web/static/assets/ldrs/
cp -R dist/* web/static/assets/ldrs/
echo "done."

