#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "build src/font.styl -> dist/index.css ..."
./node_modules/.bin/stylus -p src/font.styl > dist/index.css
echo "build src/index.styl ->> dist/index.css ..."
./node_modules/.bin/stylus -p src/index.styl >> dist/index.css
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "minifying index.css ..."
./node_modules/.bin/uglifycss dist/index.css > dist/index.min.css
echo "copy dist files to web ..."
rm -rf web/static/assets/lib/ldslider/
mkdir -p web/static/assets/lib/ldslider/dev
cp -R dist/* web/static/assets/lib/ldslider/dev/
echo "done."

