// Generated by LiveScript 1.3.1
var ldrs;
ldrs = new ldSlider({
  root: '.ldrs',
  min: 0
});
ldrs.on('change', function(it){
  return console.log('changed:', it);
});
ldrs.set(30);
ldrs = new ldSlider({
  root: ld$.find(document, '.ldrs', 1),
  min: 0
});
ldrs.on('change', function(it){
  return console.log('changed:', it);
});
ldrs.set(50);